# Change these first
owner: ThomasIAm # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: tvdn.me
    url: https://tvdn.me
  - name: wiki.tvdn.me
    url: https://wiki.tvdn.me
  - name: ai.tvdn.me
    url: https://ai.tvdn.me
  - name: old.tvdn.me
    url: https://old.tvdn.me
  - name: pp3.tvdn.me
    url: https://pp3.tvdn.me
  - name: vm2.tvdn.me
    url: https://vm2.tvdn.me

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.tvdn.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ThomasIAm/personal-site-hydejack/master/assets/global/img/logo/logo.svg
  name: TvdN | Status
  introTitle: "**Thomas van den Nieuwenhoff**'s services status."
  introMessage: This page shows the real-time status of all services hosted by Thomas van den Nieuwenhoff.
  navbar:
    - title: Status
      href: /
    - title: About
      href: https://tvdn.me/about

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

user-agent: ThomasIAm

notifications:
  - type: discord
  
assignees:
  - ThomasIAm
